spring:   

security:
    user:
        password: password
    oauth2:
        client:
            client-id: admin
            client-secret: santhu787
        resource:
            id: service
            userInfoUri: https://8000ed93-4745-4869-86ca-a93b6bbcca47.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo
            token-info-uri: https://8000ed93-4745-4869-86ca-a93b6bbcca47.predix-uaa.run.aws-usw02-pr.ice.predix.io/check_token

